export const WHATSAPP_TOKENS = {
  Config: Symbol('WhatsAppConfig'),
  WebhookSettings: Symbol('WebhookSettings'),
  WebhookSignatureVerifier: Symbol('WebhookSignatureVerifierPort'),
  WebhookEventRepository: Symbol('WebhookEventRepositoryPort'),
  WebhookEventPublisher: Symbol('WebhookEventPublisherPort'),
  VerifyWebhookSubscription: Symbol('VerifyWebhookSubscriptionPort'),
  ReceiveWebhook: Symbol('ReceiveWebhookPort'),
  InboxUnitOfWork: Symbol('InboxUnitOfWork'),
  SabaCustomers: Symbol('SabaCustomersPort'),
  ProcessWebhookEvent: Symbol('ProcessWebhookEventPort'),
  ReprocessPending: Symbol('ReprocessPendingPort'),
  ChatsRepository: Symbol('ChatsRepositoryPort'),
  WhatsAppCloud: Symbol('WhatsAppCloudPort'),
  Clock: Symbol('ClockPort'),
  ListConversations: Symbol('ListConversationsPort'),
  ListMessages: Symbol('ListMessagesPort'),
  ReplyToConversation: Symbol('ReplyToConversationPort'),
  MarkAsRead: Symbol('MarkAsReadPort'),
  GetMedia: Symbol('GetMediaPort'),
  SendTypingIndicator: Symbol('SendTypingIndicatorPort'),
  GetSabaCustomer: Symbol('GetSabaCustomerPort'),
} as const;
