export const WHATSAPP_TOKENS = {
  Config: Symbol('WhatsAppConfig'),
  WebhookSettings: Symbol('WebhookSettings'),
  WebhookSignatureVerifier: Symbol('WebhookSignatureVerifierPort'),
  WebhookEventRepository: Symbol('WebhookEventRepositoryPort'),
  WebhookEventPublisher: Symbol('WebhookEventPublisherPort'),
  VerificarSuscripcionWebhook: Symbol('VerificarSuscripcionWebhookPort'),
  RecibirWebhook: Symbol('RecibirWebhookPort'),
  InboxUnitOfWork: Symbol('InboxUnitOfWork'),
  ClientesSaba: Symbol('ClientesSabaPort'),
  ProcesarWebhookEvento: Symbol('ProcesarWebhookEventoPort'),
  ReprocesarPendientes: Symbol('ReprocesarPendientesPort'),
  ChatsRepository: Symbol('ChatsRepositoryPort'),
  WhatsAppCloud: Symbol('WhatsAppCloudPort'),
  Clock: Symbol('ClockPort'),
  ListarConversaciones: Symbol('ListarConversacionesPort'),
  ListarMensajes: Symbol('ListarMensajesPort'),
  ResponderConversacion: Symbol('ResponderConversacionPort'),
  MarcarLeida: Symbol('MarcarLeidaPort'),
  ObtenerMedia: Symbol('ObtenerMediaPort'),
  IndicarEscribiendo: Symbol('IndicarEscribiendoPort'),
  ObtenerClienteSaba: Symbol('ObtenerClienteSabaPort'),
} as const;
